### ISSUE TITLE
The sound is duplicated when I place block.

### ISSUE THREAD

**Issue by MrJorman** [Xiao-MoMi/DirectionalBlocks#4]
The sound is duplicated when I place block.

**Comment by MrJorman** [comment]
I am using BlockSound ItemsAdder plugin And when I put a block (column) then for some reason the sound is duplicated 2 times

**Comment by MrJorman** [comment]
There is no such problem with regular blocks from ItemsAdder, but when I use blocks from your plugin, the sound is buggy.

**Comment by MrJorman** [comment]
https://youtu.be/wH61Ue6NxjY

**Comment by Xiao-MoMi** [comment]
Fixed
